### PR TITLE
Implement IPv6 Dual Mode

### PR DESCRIPTION
**Pull request by queezle42**
Implements IPv6 Dual Mode as described in https://github.com/lidgren/lidgren-network-gen3/issues/32

My Visual Studio defaults use spaces instead of tabs. If you have an easy way to fix the affected lines please do so, otherwise I will fix that and create a new pull request.

### CODE REVIEW

**Comment by Addramer** [comment]
Hmm i know this is a very old topic, but i think there is an error in your changes, in
Lidgren.Network/NetUtility.cs:190 you are adding the condition "ipAddress.AddressFamily == AddressFamily.InterNetworkV6" but it should be "address.AddressFamily == AddressFamily.InterNetworkV6" as you are iterating over "addresses". I have corrected this on my personnal copy of the library, and it works.

**Comment by SteveProXNA** [comment]
@Addramer - I saw this error also and modified in my local copy

**Comment by StevePro7** [comment]
Also, to add to previous entry, NetUtility:`140 should be ipCurrent.AddressFamily == AddressFamily.InterNetworkV6 NOT ipAddress - most likely from copy + paste.

**Comment by SteveProXNA** [comment]
Also, to add to previous entry, NetUtility:`140 should be ipCurrent.AddressFamily == AddressFamily.InterNetworkV6 NOT ipAddress - most likely from copy + paste.

**Comment by SteveProXNA** [comment]
Another entry: when integrating this "IPv6 Dual Mode" code into Lidgren for our game client using the Unity game engine, the client and server communication works OK over an IPv6 network from the Unity Editor.  However, when the same code is deployed to an iOS device the Lidgren code fails to work after the NetMessageType is ConnectResponse.  

Here is the problem: NetPeer.Internal.cs HeartBeat() method fails to hydrate the m_senderRemote EndPoint object from m_socket.ReceiveFrom() over IPv6.  Thus m_senderRemote has an IPv6 address ":::0"  Then ipsender fails to downcast to IPEndPoint further on in the HeartBeat() method.  

Solution: as Client Connect() builds an IPEndPoint object from the host and port passed in, simply cache this object and reuse later as ipsender instead of receiving from the socket.  I've tested this and now the Lidgren code succeeds to work on an actual iOS device.

**Comment by SteveProXNA** [comment]
Finally, I have documented all of the above on my blog: 
Unity3D and IPv6-only Networking using Lidgren
http://steveproxna.blogspot.co.uk/2016/11/unity3d-and-ipv6-networking.html

I have referenced source code from my Github account that simulates a typical client / server networked game in IPv4-only with Lidgren code from master branch and compared the IPv6 implementation using Dual Mode pull request found here.

Source code:
IPv4 https://github.com/SteveProXNA/UnityLidgrenIPv6/tree/master/IPv4
IPv6 https://github.com/SteveProXNA/UnityLidgrenIPv6/tree/master/IPv6

**Comment by RevoluPowered** [comment]
@SteveProXNA  can you possibly send this pull request to my repo? 

I've been patching some bugs with Lidgren.

**Comment by captkirk88** [comment]
@lidgren Sorry to nudge you but could we get this merged?

**Comment by lidgren** [comment]
There's conflicting files and I'd love to see a solution that avoids creating a new heap object every time a packet is sent (yes, the library is pretty allocation heavy already, but i'd hate to add to it)

**Comment by PJB3005** [comment]
Superseded by #136

**Pull request closed without merging**
