### PR TITLE
Changed NetPeer.SendMessage parameter from List to IList

### PR DESCRIPTION
**Pull request by joshjje**

### CODE REVIEW

**Comment by lidgren** [comment]
Hey!

 

New message, please read <http://spanishliveus.com/whatever.php?ir1im>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hey!

 

Open message <http://antistatikzeminkaplama.com/sudden.php?ac0a>

 

michael@lidgren.net

**Comment by lidgren** [comment]
Hello!

 

You have a new message, please read <http://sgesoft.com/motion.php?sr>

 

michael@lidgren.net

**Comment by AgentFire** [comment]
May be `ICollection` would suffice? :)

**Comment by AgentFire** [comment]
Or even `IEnumerable` with algorythm re-write so it would run the sequence only once.

**Comment by fversnel** [comment]
Iterating using foreach on `IEnumerable` and `ICollection` in Unity generates garbage due to Unity using an old Mono version. I would prefer to use IList instead so that we can still use a `for` expression to loop. In fact I have a fork of Lidgren that replaces all `foreach` statements with a `for` loop because of this.

**Comment by lidgren** [comment]
Hello,

I've read a nice and informative article about some stuff you may really like, you can find more info here <http://ladolteslo.jeremyriley.name/aewktji>

michael@lidgren.net

**Comment by AgentFire** [comment]
@lidgren is something wrong? the link is broken for sure.

**Comment by lidgren** [comment]
Greetings! 
I haven't heard anything from you  lately, so I wanted to share with you some of my thoughts, you can read them  here <http://accept.leizar.com/aevtcx>
Thx, michael

**Pull request merged**
